site_name: Akshay Singh
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.arithmatex  # for LaTeX math support
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Projects:
      - Resume Analyzer: resume_analyzer.md
      - YT Downloader: yt_downloader.md
  - Notes:
      - Category Theory: category.md
